= Bitcoin Test Wallets Generator

A Bitcoin test wallet's generator to help bitcoin programmers.


== Features

* Generate six wallets (Alice, Bob, Carol, Dave Eve, Mallory)
* Create a json file detailing all the cryptographic materials
* Import private keys to Bitcoin Core


== Requirements

* >= NodeJS v10
* https://stedolan.github.io/jq/download/[jq - JSON processor]
* Bash or a Bash interpreter like Cygwin or Windows Subsystem for Linux (WSL)


== How to use it

First launch Bitcoin Core so that the library can import the private keys.

NOTE: By default, the library is set to the regtest network and uses hardcoded 16 bytes entropy.

 npx bitcointestwalletsgenerator

or

 git clone git@github.com:bitcoin-studio/bitcoin-test-wallets-generator.git
 node generate_wallets.js

{nbsp}

Run with a new set of entropy

NOTE: 16 bytes entropy = 12 words mnemonic +
32 bytes entropy = 24 words mnemonic

 npx bitcointestwalletsgenerator --entropy 16

{nbsp}

Set the network

 npx bitcointestwalletsgenerator --network mainnet

{nbsp}

Set the network and entropy

 npx bitcointestwalletsgenerator -n testnet -e 32

{nbsp}

Verbose

 npx bitcointestwalletsgenerator -v

{nbsp}

Help

 npx bitcointestwalletsgenerator --help

{nbsp}

Check that private key import was successful with the `listlabels` command in Bitcoin Core console
