= Bitcoin Test Wallets Generator

A Bitcoin test wallets generator to help bitcoin programmers.

== Features

* Generate six wallets (Alice, Bob, Carol, Dave Eve, Mallory)
* Create a json file detailing all the cryptographic materials
* Import private keys to Bitcoin Core

== Requirements

* >= NodeJS v10
* Bash or a Bash interpreter like Cygwin or Windows Subsystem for Linux (WSL)

== How to use it

Install

 npm install bitcointestwalletsgenerator

{nbsp}

First launch Bitcoin Core so that the library can import the private keys.

Run

NOTE: By default the library is set to the regtest network and uses hardcoded 16 bytes entropy.

 npx bitcointestwallets

{nbsp}

Run with a new set of entropy

NOTE: 16 bytes entropy = 12 words mnemonic +
32 bytes entropy = 24 words mnemonic

 npx bitcointestwallets --entropy 16

{nbsp}

Set the network

 npx bitcointestwallets --network mainnet

{nbsp}

Set the network and entropy

 npx bitcointestwallets -n testnet -e 32

{nbsp}

Help

 npx bitcointestwallets --help
